### ISSUE TITLE
Codeforces parser not working

### ISSUE THREAD

**Issue by SudhanshuBhogal** [jmerle/competitive-companion#83] opened 2020-04-17 11:44 UTC
Codeforces parser is not able to create the task JSON properly. Getting error as "Unable to parse task form JSON" in IntelliJ whenever I click the 'plus' button of the extension. Also, the extension was working fine before yesterday(16th April 2020), so I think the last commit in the codeforces parser has caused the error.
![Codeforces Parser error](https://user-images.githubusercontent.com/47147531/79565724-e281d800-80ce-11ea-95c2-d379f92269a1.jpg)

**Comment by jmerle** [comment] 2020-04-17 12:21
This is a duplicate of #82, but I'll leave this one open until 2.15.1 has been released to the Chrome Web Store.

The latest commit on the master branch on the Codeforces parser actually fixes the issue. I have just deployed 2.15.1 to Mozilla's AMO and to the GitHub releases, but the Chrome Web Store release will be delayed because I can't publish a new version on there until my latest edit to the extension's description is reviewed. I have no idea when that will happen, although I'm hopeful it happens sometime next week.

After that review is done, I can upload 2.15.1 to the Chrome Web Store as well, which also has to go through a review, so it may take a while before the new version is available on Chrome.

For now you can either use Firefox or manually install the extension on Chrome from the package provided in the latest GitHub release. See https://github.com/jmerle/competitive-companion/issues/26#issuecomment-459992662 for instructions on how to do the latter.

**Comment by huzaifa242** [comment] 2020-04-18 14:11
CodeforcesProblemParser not working for GYM problems. For normal problemset, everything is fine.

**Comment by PloadyFree** [comment] 2020-04-18 18:17
> CodeforcesProblemParser not working for GYM problems. For normal problemset, everything is fine.
> P.S. I am using Chrome extension.

I have a fix, will try to create a pull request in an hour.

**Comment by jmerle** [comment] 2020-04-22 19:21
I have just published 2.15.3 (which also contains the changes from 2.15.1 containing the bug fix) to the Chrome Web Store, which is now pending review.

**Comment by mafulafunk** [comment] 2020-04-24 10:16
I updated the extension to 2.15.3, works for me now 👍
Is there any way to throw some money at you?

**Comment by jmerle** [comment] 2020-04-24 10:39
Great to hear!
And no, I don't take donations, but if you have money laying around to throw at me feel free to throw it to a charity of your choice :)

**Closed by jmerle** 2020-04-24 10:39 UTC
