### ISSUE TITLE
NotPARSING

### ISSUE THREAD

**Issue by TezzMore** [jmerle/competitive-companion#415] opened 2024-01-25 13:30 UTC
Competitve Companion is not able to parse the problem to the VS Code from Codechef.

VM62 common.js:1 TypeError: Cannot read properties of null (reading 'textContent')
    at CodeChefNewProblemParser.parse (VM62 common.js:1:383899)
    at p (content.js:1:580)
    at content.js:1:1510

This is the response written in the browser Console when I am clicking the '+' icon.Hoping that the issue is a minor one and gets solved quickly:)

**Comment by jmerle** [comment] 2024-01-25 13:44
This is a duplicate of #410, for which the fix was already released in version [2.50.0](https://github.com/jmerle/competitive-companion/releases/tag/2.50.0).

**Closed by jmerle** 2024-01-25 13:44 UTC
