### ISSUE TITLE
Don't work with leetcode

### ISSUE THREAD

**Issue by yousefsayedd1** [jmerle/competitive-companion#394] opened 2023-11-09 23:08 UTC

**Comment by jmerle** [comment] 2023-11-09 23:17
This is a duplicate of [many other issues](https://github.com/jmerle/competitive-companion/issues?q=is%3Aissue+sort%3Aupdated-desc+LeetCode+OR+Leet), please see #245 for more information.

**Closed by jmerle** 2023-11-09 23:17 UTC
