### ISSUE TITLE
Support for CodingNinjas

### ISSUE THREAD

**Issue by taaaahahaha** [jmerle/competitive-companion#379] opened 2023-09-28 14:34 UTC
It would be great if the extension works for problem parsing with Coding Ninjas

**Comment by jmerle** [comment] 2023-09-28 14:46
This is a duplicate of #184 and #366. Coding Ninjas seems to require code to be written in pre-defined methods, which is incompatible with Competitive Companion's format, so a Coding Ninjas parser won't be added. See #245 for more information.

**Closed by jmerle** 2023-09-28 14:46 UTC
