### ISSUE TITLE
Not working on CodeChef now!!!

### ISSUE THREAD

**Issue by pavankumar4404** [jmerle/competitive-companion#416] opened 2024-01-26 18:24 UTC
Last week it was working perfectly in codechef but from this week it's not working. It's giving this error :
"Something went wrong while running Competitive Companion's CodeChefNewProblemParser. Open the browser console to see the error. Please open an issue at https://github.com/jmerle/competitive-companion/issues if you think this is a bug (make sure to include a link to this page)."

**Comment by Xylecrack** [comment] 2024-01-26 19:21
The console shows this error:
![image](https://github.com/jmerle/competitive-companion/assets/143005511/085fab1c-a600-454f-942e-9a5979b3e4ed)

**Comment by jmerle** [comment] 2024-01-26 22:19
This is a duplicate of #410, for which the fix was already released in version [2.50.0](https://github.com/jmerle/competitive-companion/releases/tag/2.50.0).

**Closed by jmerle** 2024-01-26 22:19 UTC
