### ISSUE TITLE
Can't Parse with CodeChefContest

### ISSUE THREAD

**Issue by atandrit** [jmerle/competitive-companion#421] opened 2024-02-01 10:34 UTC
Having problem while trying to parse the question on CodeChef. Link: https://www.codechef.com/

**Comment by jmerle** [comment] 2024-02-01 14:00
This is a duplicate of #410, for which the fix was already released in version [2.50.0](https://github.com/jmerle/competitive-companion/releases/tag/2.50.0).

**Closed by jmerle** 2024-02-01 14:00 UTC
