### ISSUE TITLE
there is no parser for geeksforgeek

### ISSUE THREAD

**Issue by Singh-Sanchit** [jmerle/competitive-companion#220] opened 2022-01-21 14:21 UTC
Not able to parse https://practice.geeksforgeeks.org/problems/minimum-steps-to-make-product-equal-to-one/1/#

**Comment by jmerle** [comment] 2022-02-17 17:19
This is a duplicate of #44, #115, and #212.

**Closed by jmerle** 2022-02-17 17:19 UTC
