### ISSUE TITLE
do not work in greeksforgreeeks problemset

### ISSUE THREAD

**Issue by talha-khondoker** [jmerle/competitive-companion#490] opened 2024-09-10 03:52 UTC
https://www.geeksforgeeks.org/problems/count-digits5716/1
 I am trying to open this type of problem but it is not working

**Comment by jmerle** [comment] 2024-09-20 20:17
This is a duplicate of [many other issues](https://github.com/jmerle/competitive-companion/issues?q=is%3Aissue+sort%3Aupdated-desc+GeeksforGeeks+OR+Geeks), please see #245 for more information.

**Closed by jmerle** 2024-09-20 20:17 UTC
