### ISSUE TITLE
Library Checker Problem Parsing

### ISSUE THREAD

**Issue by aadarshkt** [jmerle/competitive-companion#289] opened 2022-08-19 10:51 UTC
I am getting a error while parsing a problem on Library Checker Website.

![Screenshot from 2022-08-19 16-16-35](https://user-images.githubusercontent.com/72285744/185603015-c8d25fdf-11b9-4922-8e35-88a3379422aa.png)

[Link to the problem](https://judge.yosupo.jp/problem/unionfind)

Console says this.

![image](https://user-images.githubusercontent.com/72285744/185603230-fd17dc04-dd62-4897-9c70-9939f0ca5692.png)

**Comment by jmerle** [comment] 2022-08-26 13:00
I cannot reproduce this issue, and I think it was fixed by #281 which was released in 2.36.0. Can you please make sure you are using at least version 2.36.0 (right-click the green plus icon > Manage extension) and then check if you can still reproduce the issue?

**Comment by jmerle** [comment] 2022-09-30 01:11
I'm closing this issue because of inactivity. Feel free to open a new issue if you still see errors.

**Closed by jmerle** 2022-09-30 01:11 UTC
