### ISSUE TITLE
Extension not working for geeksforgeeks 

### ISSUE THREAD

**Issue by veerviren** [jmerle/competitive-companion#334] opened 2023-02-26 16:31 UTC

**Comment by jmerle** [comment] 2023-02-26 17:22
This is a duplicate of [many other issues](https://github.com/jmerle/competitive-companion/issues?q=is%3Aissue+sort%3Aupdated-desc+LeetCode+OR+Leet+OR+GeeksforGeeks+OR+Geeks), please see #245 for more information.

**Closed by jmerle** 2023-02-26 17:22 UTC
