### ISSUE TITLE
[CodeForces] Parsing issue

### ISSUE THREAD

**Issue by venkatvb** [jmerle/competitive-companion#30] opened 2019-03-22 17:25 UTC
Hi,

Thanks for developing the competitive-companion plugin. Its amazing! ❤️  

I found an issue while parsing [this problem from codeforces.com](https://codeforces.com/contest/1140/problem/B).
 
Special characters like `>` and `<` in the test cases are not parsed properly

I expected the parsed output to be:

```
3
2
<>
3
><<
1
>

```

Actual parsed output:

```
3
2
&lt;&gt;
3
&gt;&lt;&lt;
1
&gt;
```

P.S: I'm using [Highttail](https://github.com/dj3500/hightail/) along with competitive-companion plugin

**Comment by jmerle** [comment] 2019-03-22 17:37
Duplicate of #28, already fixed on the develop branch and will be released in a few hours. Thanks for the report and the kind words though.

**Closed** 2019-03-22 17:37 UTC
