### ISSUE TITLE
not parsing anymore

### ISSUE THREAD

**Issue by krsinghshubham** [jmerle/competitive-companion#111] opened 2020-08-01 18:19 UTC
the extension is not able to parse any of the contest/ problems on codeforces/atcoder etc on either of the browsers.

issue: just a green and black bar glows up after that nothing happens.

**Comment by jmerle** [comment] 2020-08-02 01:38
I cannot reproduce this problem, and given that you're the only one reporting the Codeforces parser is broken I am guessing this is an issue with the tool you're using (and not with the extension).

To see if that hypothesis is correct, could you please turn on debug mode (right-click on the plus icon > Options > Debug mode), go to the problem page again, open the browser's console (F12) and screenshot its output after having parsed the problem?

**Comment by RachitG001** [comment] 2020-08-02 15:06
Hey, i am also facing the same issue. Unable to parse problems from any site. I have attached the debug screenshot too.
@jmerle 
<img width="1440" alt="Screenshot 2020-08-02 at 8 31 59 PM" src="https://user-images.githubusercontent.com/34421323/89125897-3a6a1080-d4ff-11ea-8ae0-3a0ad1d517c0.png">

**Comment by jmerle** [comment] 2020-08-02 15:13
@RachitG001 The first message in the browser console in your screenshot confirms that the extension is working correctly (the error is not coming from the extension). You should contact the developer of the tool you're using.

**Comment by krsinghshubham** [comment] 2020-08-02 17:25
1. i am getting the following error in console !
   Attaching the screenshot.

![2 august Annotation 2020-08-02 224222](https://user-images.githubusercontent.com/47324260/89128428-229c8780-d513-11ea-8145-d84bda7e04ad.png)




2. getting extra two errors when website tracking is on, trackers are being blocked from facebook and google-analytics. Is it necessary to keep the trackers off ?

**Comment by jmerle** [comment] 2020-08-02 17:38
1:
I got a few follow-up questions because I cannot reproduce it in Chrome myself:
1. Is Competitive Companion's debug mode turned on in that screenshot?
2. What browser are you using in that screenshot? My Chrome and Firefox look a lot different (especially the order of elements in the top bar).

2: Ad and/or tracker blockers should not cause problems.

**Comment by krsinghshubham** [comment] 2020-08-02 17:47
1. yes extension's debug mode is on.
2. i am using microsoft edge based on chromium.
3. Although i checked, exactly same error is there is chrome's log too.
4. attaching a screenshot from chrome too although my primary browser is Edge only.
![2 aug -2Annotation 2020-08-02 231505](https://user-images.githubusercontent.com/47324260/89128874-40b7b700-d516-11ea-9be8-e555326a4a89.png)

**Comment by jmerle** [comment] 2020-08-07 09:07
Hmm, I'm completely unable to reproduce this bug. Could you try isolating Competitive Companion in Edge to ensure the problem is not in the combination of extensions you are using? You can do this by right-clicking on the plus icon, selecting "Extension options", closing the settings dialog and then enabling "Allow in InPrivate". Then, make sure no other extension has "Allow in InPrivate" checked (you can check by opening the extensions list using the "Installed extensions" link in the top-right and checking the "Details" for each extension) and open an incognito window (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>N</kbd>), which should only have Competitive Companion enabled if you followed these steps. Can you still reproduce the bug in this incognito window?

**Comment by krsinghshubham** [comment] 2020-08-10 12:39
![10 aug Annotation 2020-08-10 180347](https://user-images.githubusercontent.com/47324260/89783055-ee891e00-db33-11ea-8d7f-ac9a16ff6e8a.png)


so , after removing all of the auto activating extensions , 
there are no more errors in log, BUT the extension is not doing any thing apart from a sliding bar on top ?
Do i manually need to open any folder in vsc ?

**Comment by jmerle** [comment] 2020-08-10 12:44
What you're seeing is the expected output. Competitive Companion only parses problems and sends the extracted data to external tools (like CHelper, JHelper, Hightail, acmX and others). What you're seeing in the console is the data that is being sent, but if you are not using a tool which listens for data from the extension, you won't see anything happening apart from the sliding bar on top.

Anyhow, that screenshot does verify that the issue you're facing comes from the combination of using Competitive Companion with an unknown other extension. The only way to know for sure which one is causing the problem is by enabling all disabled extensions one-by-one, constantly checking if Competitive Companion still provides the expected output (what you're seeing in your latest screenshot).

**Comment by krsinghshubham** [comment] 2020-08-10 12:52
i am using acmx and the port is same for both the tool and extension, still there is no response from the tool. will close the issue from my side after getting a confirmation from acmx's developer. please wait till then.

**Comment by jmerle** [comment] 2020-08-27 19:43
Closing this issue due to inactivity.

**Closed by jmerle** 2020-08-27 19:43 UTC
