### ISSUE TITLE
support for coding ninjas platform

### ISSUE THREAD

**Issue by venkat2305** [jmerle/competitive-companion#366] opened 2023-06-20 18:22 UTC
Can you please add support for this website: https://www.codingninjas.com/codestudio/problems/subset-sum_3843086?topList=striver-sde-sheet-problems

I'm following Striver's SDE sheet, which is a popular resource for coding interview preparation. It has questions linked to this website, and many students are using it to practice data structures and algorithms. It would be great if your platform is compatible with it.

Thank you for your consideration.

**Comment by jmerle** [comment] 2023-06-20 19:21
This is a duplicate of #184 and the answer is still the same. Coding Ninjas seems to require code to be written in pre-defined methods, which is incompatible with Competitive Companion's format, so a Coding Ninjas parser won't be added. See #245 for more information.

**Closed by jmerle** 2023-06-20 19:21 UTC
