### ISSUE TITLE
Codeforces new sample display

### ISSUE THREAD

**Issue by xhgua** [jmerle/competitive-companion#284] opened 2022-08-10 14:29 UTC
https://codeforces.com/blog/entry/105779
This will cause the plugin to crawl down a string of HTML code when crawling the CF sample.
Hope to fix it soon.

我不会英文，所以是机器翻译的.
I don't know English, so it's machine translation.

**Comment by jmerle** [comment] 2022-08-10 14:39
This is a duplicate of #277 which was fixed in version 2.35.3. It seems like your browser hasn't auto-updated the extension yet, you can force an update by re-installing the extension.

**Closed by jmerle** 2022-08-10 14:39 UTC
