### ISSUE TITLE
Parser support missing for GeeksforGeeks Practice section and Leetcode

### ISSUE THREAD

**Issue by divyansh000915** [jmerle/competitive-companion#233] opened 2022-03-09 07:26 UTC

**Comment by adarsh-dhakad** [comment] 2022-03-11 02:03
yes how to use leetcode

**Comment by jmerle** [comment] 2022-03-26 17:01
This is a duplicate of #44, #156, #201, #164, #201, #213, and a few others.

**Closed by jmerle** 2022-03-26 17:01 UTC
