### ISSUE TITLE
leetcode error

### ISSUE THREAD

**Issue by Imran-2022** [jmerle/competitive-companion#456] opened 2024-05-11 15:02 UTC
somehow not working with leetcode !!

**Comment by jmerle** [comment] 2024-05-11 15:06
This is a duplicate of [many other issues](https://github.com/jmerle/competitive-companion/issues?q=is%3Aissue+sort%3Aupdated-desc+LeetCode+OR+Leet), please see #245 for more information.

**Closed by jmerle** 2024-05-11 15:06 UTC
