### ISSUE TITLE
Chrome: an empty request is sent.

### ISSUE THREAD

**Issue by GoBigorGoHome** [jmerle/competitive-companion#105] opened 2020-07-06 12:36 UTC
I use Competitive Companion in Chrome along with [JHelper](https://github.com/AlexeyDmitriev/jhelper/). JHelper has a `ServerSocket` listen on port 4243, it works like
```java
while (true) {
  try {
    // ...
    try (Socket socket = serverSocket.accept()) {
      InputStream inputStream = socket.getInputStream();
      String request = readFromStream(inputStream);
      // I added the following line for debug purpose.
      // System.out.println("BEGIN: " + request);
      String[] strings = request.split("\n\n", 2);

      //ignore headers
      if (strings.length < 2) {
        Notificator.showNotification(
          "ChromeParser",
          "Got response without body. Ignore.",
          NotificationType.INFORMATION
        );
        continue;
      }
      // ....
    }
  } catch (IOException ignored) {}
}
``` 
The first task is added just fine. For each of the subsequent tasks added, before the task data is sent, the CC extension sends an empty request, so the `if (strings.length < 2)` branch in the above code executes and a notification pops up in CLion.

The following is how I found this:
In the above code fragment, I added the `System.out.println("BEGIN: " + request);` statment. For the first task added, the output is
```
BEGIN: POST / HTTP/1.1
Host: localhost:4243
Connection: keep-alive
Content-Length: 491
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
Content-Type: text/plain;charset=UTF-8
Accept: */*
Origin: chrome-extension://cjnmckjndlpiamhfimnnjmnckgghkjbl
Sec-Fetch-Site: none
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9

json
{"name":"H. Set Merging","group":"Codeforces - Codeforces Global Round 9","url":"https://codeforces.com/contest/1375/problem/H","interactive":false,"memoryLimit":256,"timeLimit":4000,"tests":[{"input":"3 2\n1 3 2\n2 3\n1 3\n","output":"6\n3 2\n1 3\n5 2\n4 6 \n"},{"input":"2 4\n2 1\n1 2\n1 2\n1 2\n1 1\n","output":"5\n2 1\n2 1\n2 1\n5 3 3 1\n"}],"testType":"single","input":{"type":"stdin"},"output":{"type":"stdout"},"languages":{"java":{"mainClass":"Main","taskClass":"HSetMerging"}}}

```
Then for the second task added, the output is 
```
BEGIN: 
BEGIN: POST / HTTP/1.1
Host: localhost:4243
Connection: keep-alive
Content-Length: 532
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
Content-Type: text/plain;charset=UTF-8
Accept: */*
Origin: chrome-extension://cjnmckjndlpiamhfimnnjmnckgghkjbl
Sec-Fetch-Site: none
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9

json
{"name":"I. Cubic Lattice","group":"Codeforces - Codeforces Global Round 9","url":"https://codeforces.com/contest/1375/problem/I","interactive":false,"memoryLimit":256,"timeLimit":4000,"tests":[{"input":"2\n1 2 3\n1 2 1\n","output":"1\n1 0 0\n0 1 0\n0 0 1\n"},{"input":"1\n1 2 2\n","output":"9\n2 -2 1\n1 2 2\n-2 -1 2\n"},{"input":"1\n2 5 5\n","output":"9\n-1 2 2\n2 -1 2\n2 2 -1\n"}],"testType":"single","input":{"type":"stdin"},"output":{"type":"stdout"},"languages":{"java":{"mainClass":"Main","taskClass":"ICubicLattice"}}}

```

The extension in Firefox does NOT have this problem, so I think this is not an issue of JHelper.

**Comment by jmerle** [comment] 2020-07-06 22:34
I cannot reproduce this issue on Chrome 83 with JHelper 0.18. This is going to be a bit technical, but I'm wondering whether the empty requests are actually coming from Competitive Companion. Can you try the following?:
1. Right-click on the plus icon
2. Click on Manage extensions
3. Enable Developer Mode in the top-right
4. Click on the "background page" link underneath "Inspect views"
5. Open the Network tab in the DevTools window that opens
6. Reproduce the bug again, and check whether the empty request is visible in the Network tab of the background page (all requests Competitive Companion makes to localhost ports show up here)

**Comment by GoBigorGoHome** [comment] 2020-07-06 23:02
The requests listed in the Network tab look all right, there is no empty request to localhost:4243.

Can you please suggest some possible causes for this issue?

**Comment by jmerle** [comment] 2020-07-06 23:13
That pretty much rules out it being a bug in the extension.

The only thing I can think of is there being a conflicting extension on Chrome. You could try allowing the extension to run in incognito (on the same Manage extensions page there is a toggle for that) and see if the bug occurs in incognito tabs as well.

**Comment by GoBigorGoHome** [comment] 2020-07-06 23:48
Running the extension in incognito window brings no change :(

According to the doc, the `accept()` method of the `ServerSocket` class
> listens for a connection to be made to this socket and accepts it. The method blocks until a connection is made.

How can I know who made that connection?

**Comment by GoBigorGoHome** [comment] 2020-07-07 23:19
@jmerle @AlexeyDmitriev  I found that the empty request was from Chrome's process named "Utility: Network service".

The following  code fragment is from JHelper, [full version](https://github.com/AlexeyDmitriev/JHelper/blob/master/src/name/admitriev/jhelper/network/SimpleHttpServer.java). I've added some `System.out.println()`s to debug.

```java
public class SimpleHttpServer implements Runnable {
         // ...
	@Override
	public void run() {
		while (true) {
			try {
                // ...
				System.out.println("Waiting for client on port " + serverSocket.getLocalPort() + "...");
				try (Socket socket = serverSocket.accept()) {
					System.out.println("Just connected to " + socket.getRemoteSocketAddress());
					InputStream inputStream = socket.getInputStream();
					String request = readFromStream(inputStream);
					System.out.println("BEGIN: " + request);
					String[] strings = request.split("\n\n", 2);

					//ignore headers
					if (strings.length < 2) {
						Notificator.showNotification(
								"ChromeParser",
								"Got response without body. Ignore.",
								NotificationType.INFORMATION
						);
						continue;
					}
					// ...
				}
			}
			catch (IOException ignored) {
			}
		}
	}

	private static String readFromStream(InputStream inputStream) throws IOException {
		try (BufferedReader reader = new BufferedReader(
				new InputStreamReader(inputStream, "UTF-8")
		)) {
			StringBuilder builder = new StringBuilder();
			String line;
			//noinspection NestedAssignment
			while ((line = reader.readLine()) != null)
				builder.append(line).append('\n');
			return builder.toString();
		}
	}
        // ...
}
```

Following is the output, for brevity, the headers and json of the requests from competitive companion is omitted:

1. Start CLion

   ```
   Waiting for client on port 4243...
   ```

2. Add a task

   ```
   Just connected to /127.0.0.1:6265
   BEGIN: <headers>
   
   json
   <json>
   
   Waiting for client on port 4243...
   Just connected to /127.0.0.1:6267
   ```

   After the request from competitive companion, the second connection is from 127.0.0.1:6267. Now inside the `readFromStream()` method, the function call `reader.readLine()` blocks.

   On my Windows 10 machine, in CMD, `netstat -ano | findstr "6267"` shows

   ```
     TCP    127.0.0.1:4243         127.0.0.1:6267         ESTABLISHED     1880
     TCP    127.0.0.1:6267         127.0.0.1:4243         ESTABLISHED     12584
   ```

   Then `tasklist /fi "pid eq 12854"` shows

   ```
   Image Name                     PID Session Name        Session#    Mem Usage
   ========================= ======== ================ =========== ============
   chrome.exe                   12584 Console                    1     45,992 K
   ```

   Finally, look up PID 12854 in Chrome's task manager, it is a task named "Utility: Network Service".

3. Add another task

   ```
   BEGIN: 
   Waiting for client on port 4243...
   Just connected to /127.0.0.1:6589
   BEGIN: <headers>
   
   json
   <json>
   
   Waiting for client on port 4243...
   Just connected to /127.0.0.1:6591
   ```

   Again, 127.0.0.1:6591 is Chrome's "Utility: Network Service".

   ----

   Why does Chrome's Network Service make a connection to JHelper?  Does it  have anything to do with competitive companion?

   Another question might be off-topic here, why does `reader.Readline()` stop blocking when adding the second task?

**Comment by AlexeyDmitriev** [comment] 2020-07-08 09:42
From what I've read (in Russian) this is some kind of Chrome's experiment. Do you have "Enable network service" in chrome://flags/ ? I don't see it, but maybe it's because I'm not in the expirement. You can try disabling it if it's there

**Comment by jmerle** [comment] 2020-07-09 13:06
I'm closing this issue as I deem it unlikely that this is a bug in Competitive Companion.

**Closed by jmerle** 2020-07-09 13:06 UTC

**Comment by GoBigorGoHome** [comment] 2020-07-10 09:10
@AlexeyDmitriev There is not such an opiton as "Enable network service" in Chrome 83, there is an option "Runs network service in-process." though, but it does not help to change its value.

I've made a custom build of JHelper with the notification removed.

**Comment by GoBigorGoHome** [comment] 2020-07-10 09:14
@jmerle Although this is unlikely a bug in Competive Companion, it does seem like a bug in the interaction between the extension and Chrome.

**Comment by jmerle** [comment] 2020-07-10 11:25
In your case that statement does seem to be true, but considering 90% of Competitive Companion's users are using Chrome and considering this issue would break more tools than just CHelper, I highly doubt that this issue is widespread. All I can guess is that you are part of an A/B-test, which I can't do anything against.

If more people report the same issue I'll look deeper into it, but for now I don't think there is anything I can do.

**Comment by AlexeyDmitriev** [comment] 2020-07-10 11:36
@GoBigorGoHome I guess the easiest thing for you now is to ignore notification.
