### ISSUE TITLE
Add support for Leetcode

### ISSUE THREAD

**Issue by vens8** [jmerle/competitive-companion#201] opened 2021-11-07 16:10 UTC
Competitive Companion currently isn't able to parse problems on Leetcode. Please consider adding it. Thank you.

**Comment by jmerle** [comment] 2021-11-07 16:24
This is a duplicate of #156 and #164. LeetCode requires code to be written in pre-defined methods, which does not fit in Competitive Companion's format, so a LeetCode parser won't be added.

**Closed by jmerle** 2021-11-07 16:24 UTC
