### ISSUE TITLE
competative-companion not working in codechef contest

### ISSUE THREAD

**Issue by Melkor786** [jmerle/competitive-companion#414] opened 2024-01-25 11:22 UTC
It is showing this error in console on parsing
![Screenshot 2024-01-25 165133](https://github.com/jmerle/competitive-companion/assets/97447229/1e968fe4-88df-4928-aa42-814d9a0fd26a)

TypeError: elem.querySelector(...) is null
    parse moz-extension://53b14dd5-dbe8-46ca-8b8d-f48814328945/js/content.js:29
    parse moz-extension://53b14dd5-dbe8-46ca-8b8d-f48814328945/js/content.js:47
    handleMessage moz-extension://53b14dd5-dbe8-46ca-8b8d-f48814328945/js/content.js:47
    promise callback*handleMessage moz-extension://53b14dd5-dbe8-46ca-8b8d-f48814328945/js/content.js:47
[content.js:47:6103](moz-extension://53b14dd5-dbe8-46ca-8b8d-f48814328945/js/content.js)
    parse moz-extension://53b14dd5-dbe8-46ca-8b8d-f48814328945/js/content.js:47
    handleMessage moz-extension://53b14dd5-dbe8-46ca-8b8d-f48814328945/js/content.js:47
    (Async: promise callback)
    handleMessage moz-extension://53b14dd5-dbe8-46ca-8b8d-f48814328945/js/content.js:47

**Comment by jmerle** [comment] 2024-01-25 11:47
This is a duplicate of #410, for which the fix was already released in version [2.50.0](https://github.com/jmerle/competitive-companion/releases/tag/2.50.0).

**Closed by jmerle** 2024-01-25 11:47 UTC
