### ISSUE TITLE
Can not use this in geeksforgeeks.com and leetcode.com.

### ISSUE THREAD

**Issue by tonmoy197** [jmerle/competitive-companion#242] opened 2022-04-24 16:28 UTC

**Comment by krishnakumarg1984** [comment] 2022-05-19 13:38
Bump this.

**Comment by jmerle** [comment] 2022-05-21 21:54
This is a duplicate of [many other issues](https://github.com/jmerle/competitive-companion/issues?q=is%3Aissue+sort%3Aupdated-desc+LeetCode+OR+Leet+OR+GeeksforGeeks+OR+Geeks), please see #245 for more information.

**Closed by jmerle** 2022-05-21 21:54 UTC
