### ISSUE TITLE
not working for leetcode problems

### ISSUE THREAD

**Issue by kalyugkacoder** [jmerle/competitive-companion#384] opened 2023-10-08 15:52 UTC

**Comment by jmerle** [comment] 2023-10-09 01:21
This is a duplicate of [many other issues](https://github.com/jmerle/competitive-companion/issues?q=is%3Aissue+sort%3Aupdated-desc+LeetCode+OR+Leet), please see #245 for more information.

**Closed by jmerle** 2023-10-09 01:21 UTC
