### ISSUE TITLE
CodeChefNewProblemParser not working anymore

### ISSUE THREAD

**Issue by theabbie** [jmerle/competitive-companion#305] opened 2022-11-23 14:57 UTC
![image](https://user-images.githubusercontent.com/17960677/203578115-99b3912c-f039-4a62-8e41-fdf822b9e17b.png)

Link: https://www.codechef.com/START66B/problems/GOODBINSTR

**Comment by jmerle** [comment] 2022-11-23 15:02
This is a duplicate of #302 and #303.

**Closed by jmerle** 2022-11-23 15:02 UTC
