### ISSUE TITLE
unable to parse

### ISSUE THREAD

**Issue by Ankitraj2003** [jmerle/competitive-companion#322] opened 2023-01-01 14:50 UTC
does not work with gfg and leetcode

**Comment by jmerle** [comment] 2023-01-01 14:53
This is a duplicate of [many other issues](https://github.com/jmerle/competitive-companion/issues?q=is%3Aissue+sort%3Aupdated-desc+LeetCode+OR+Leet+OR+GeeksforGeeks+OR+Geeks), please see #245 for more information.

**Closed by jmerle** 2023-01-01 14:53 UTC
