### ISSUE TITLE
Leetcode: not parsing question inside a series

### ISSUE THREAD

**Issue by ShivamS136** [jmerle/competitive-companion#479] opened 2024-07-28 14:13 UTC
Page URL: https://leetcode.com/problems/text-justification/description/?envType=study-plan-v2&envId=top-interview-150

Getting error:

```
Competitive Companion could not determine which parser to parse this page with. Please right-click on the plus icon and select the parser to use via the "Parse with" context menu. Please open an issue at https://github.com/jmerle/competitive-companion/issues if you think this is a bug (make sure to include a link to this page).
```

**Comment by ShivamS136** [comment] 2024-07-28 14:14
Page screenshot:

![image](https://github.com/user-attachments/assets/2bd46191-d042-4004-b534-d414f2cb3e8c)

**Comment by jmerle** [comment] 2024-07-28 14:15
This is a duplicate of [many other issues](https://github.com/jmerle/competitive-companion/issues?q=is%3Aissue+sort%3Aupdated-desc+LeetCode+OR+Leet), please see #245 for more information.

**Closed by jmerle** 2024-07-28 14:15 UTC
