### ISSUE TITLE
issue while using codechef.

### ISSUE THREAD

**Issue by raghusuresh** [jmerle/competitive-companion#248] opened 2022-05-24 13:32 UTC
It is not working when i am using CodeChef.I have tried many times but it is giving an error every time. Please fix this problem.

**Comment by jmerle** [comment] 2022-05-25 22:43
I have no idea what's going wrong since you haven't shared the error, but I'm going to assume you tried parsing a problem from a `https://www.codechef.com/submit-v2/<problem code>` URL (i.e. the new problem interface), in which case this is a duplicate of #246.

**Closed by jmerle** 2022-05-25 22:43 UTC
