### ISSUE TITLE
Doesn't support leetcode

### ISSUE THREAD

**Issue by sheikh-mohammad-rakib** [jmerle/competitive-companion#493] opened 2024-09-24 14:01 UTC
![leetcode](https://github.com/user-attachments/assets/a5239ee9-1ac6-453d-a6fe-fc6cef7a060b)

**Comment by sheikh-mohammad-rakib** [comment] 2024-09-24 14:12
[https://leetcode.com/problems/merge-sorted-array/?envType=study-plan-v2&envId=top-interview-150](url)

**Comment by jmerle** [comment] 2024-09-25 07:04
This is a duplicate of [many other issues](https://github.com/jmerle/competitive-companion/issues?q=is%3Aissue+sort%3Aupdated-desc+LeetCode+OR+Leet), please see #245 for more information.

**Closed by jmerle** 2024-09-25 07:04 UTC
