### ISSUE TITLE
Support for GFG

### ISSUE THREAD

**Issue by kshitij-srivastav** [jmerle/competitive-companion#241] opened 2022-04-21 15:57 UTC
Please provide this extension for GFG and leet code

**Comment by jmerle** [comment] 2022-05-21 21:54
This is a duplicate of [many other issues](https://github.com/jmerle/competitive-companion/issues?q=is%3Aissue+sort%3Aupdated-desc+LeetCode+OR+Leet+OR+GeeksforGeeks+OR+Geeks), please see #245 for more information.

**Closed by jmerle** 2022-05-21 21:54 UTC
