### ISSUE TITLE
codeforces updated their input tab visualization... the extension is fetching garbage values(html) with the input

### ISSUE THREAD

**Issue by stunnerhash** [jmerle/competitive-companion#279] opened 2022-08-09 15:44 UTC
codeforces just updated their input output tab visualization... now compatitive companion parses the input box and takes up a whole html text, update it accordingly,

**Comment by jmerle** [comment] 2022-08-09 15:54
This is a duplicate of #277 which was fixed in version 2.35.3. You can either wait for your browser to auto-update the extension (usually happens within 24 hours after an update, the extension was updated 20 hours ago) or force an update by re-installing the extension.

**Closed by jmerle** 2022-08-09 15:54 UTC
