### ISSUE TITLE
Not working with Hightail and CHelper.

### ISSUE THREAD

**Issue by NAbdulla1** [jmerle/competitive-companion#90] opened 2020-04-23 11:08 UTC
I think after the latest update it is not working with the Hightail tool and CHelper. Am I right? or it is a problem in my system. It is working with 'Competitive Programming Helper'.

**Comment by NAbdulla1** [comment] 2020-04-23 12:12
I have found the problem. While parsing the JSON "Hightail" gives an exception `JSONObject["timeLimit"] is not an int.`  in it handlesRequest method on file HttpServer.java
After inspecting the JSON that is sent by 'Competitive Companion', it seems that it sets both the memory limit and time limit to `null`. Please see the problem.

![image](https://user-images.githubusercontent.com/21087073/80097950-eb225480-858d-11ea-9aac-89ffed87371e.png)

**Comment by jmerle** [comment] 2020-04-23 12:17
Duplicate of #83 and #82.

**Closed by jmerle** 2020-04-23 12:17 UTC

**Comment by NAbdulla1** [comment] 2020-04-24 04:25
Sorry, Sir.
