### ISSUE TITLE
Extension not working for Leetcode

### ISSUE THREAD

**Issue by shivendr7** [jmerle/competitive-companion#353] opened 2023-05-23 03:43 UTC

**Comment by jmerle** [comment] 2023-05-28 19:26
This is a duplicate of [many other issues](https://github.com/jmerle/competitive-companion/issues?q=is%3Aissue+sort%3Aupdated-desc+LeetCode+OR+Leet), please see #245 for more information.

**Closed by jmerle** 2023-05-28 19:26 UTC
