### ISSUE TITLE
support for leetcode required

### ISSUE THREAD

**Issue by rajeshtva** [jmerle/competitive-companion#239] opened 2022-04-09 04:46 UTC
This parser is not parsing the leetcode ui for questions.

**Comment by KorigamiK** [comment] 2022-05-21 04:48
Please check #244

**Comment by jmerle** [comment] 2022-05-21 21:54
This is a duplicate of [many other issues](https://github.com/jmerle/competitive-companion/issues?q=is%3Aissue+sort%3Aupdated-desc+LeetCode+OR+Leet), please see #245 for more information.

**Closed by jmerle** 2022-05-21 21:54 UTC
