### ISSUE TITLE
Not Working for Codechef

### ISSUE THREAD

**Issue by VampireQuestt** [jmerle/competitive-companion#264] opened 2022-07-18 13:06 UTC
Something went wrong while running Competitive Companion's CodeChefNewProblemParser. Open the browser console to see the error. Please open an issue at https://github.com/jmerle/competitive-companion/issues if you think this is a bug.

**Comment by jmerle** [comment] 2022-07-18 13:13
This is a duplicate of https://github.com/jmerle/competitive-companion/issues/250#issuecomment-1186421216 and will be fixed in the next release.

**Closed by jmerle** 2022-07-18 13:13 UTC
